CREATE DATABASE MYDB1

USE MYDB1

CREATE TABLE MYTAB1
(
    ROLLNO INT,
    FIRSTNAME VARCHAR (50),
    LASTNAME VARCHAR (50),

)

USE MYDB1
SELECT ROLLNO, FIRSTNAME, LASTNAME FROM MYTAB1

INSERT INTO MYTAB1 (ROLLNO, FIRSTNAME, LASTNAME)
VALUES(1, 'DEVA', 'CHANDRAGIRI')

USE AdventureWorks2012

SELECT * FROM [HumanResources].[Department]

SELECT NAME FROM [HumanResources].[Department]

SELECT GroupName FROM [HumanResources].[Department]

SELECT DISTINCT GROUPNAME FROM [HumanResources].Department

SELECT NAME, GROUPNAME FROM [HumanResources].Department
WHERE GroupName LIKE 'MANUFACTURING'

SELECT * FROM HumanResources.Employee

SELECT * FROM HumanResources.Employee WHERE OrganizationLevel=1

USE AdventureWorks2012

SELECT * FROM HumanResources.Employee WHERE JobTitle LIKE '%PRESIDENT%'

SELECT * FROM HumanResources.Employee WHERE BirthDate >  '1/1/1990'

SELECT * FROM HumanResources.Employee WHERE BirthDate BETWEEN '1/1/1990' AND '1/1/2000'

SELECT NAME, LISTPRICE FROM Production.Product 

SELECT NAME, LISTPRICE, LISTPRICE + 10 AS UPDATED_LISTPRICE FROM Production.Product

SELECT NAME, LISTPRICE, LISTPRICE + 23 AS UPDATED_LISTPRICE INTO #TEMPYTAB FROM Production.Product

SELECT * FROM #TEMPYTAB 

DELETE FROM #TEMPYTAB
WHERE NAME LIKE 'Bearing Ball'

SELECT * FROM #TEMPYTAB

UPDATE #TEMPYTAB
SET NAME = 'BLADE_2'
WHERE NAME LIKE 'BLADE'

SELECT * FROM #TEMPYTAB

CREATE TABLE #TOPEMPLOYEEDETAILS (EMPLOYEE_ID INT, FIRSTNAME VARCHAR (20), LASTNAME VARCHAR (20))

INSERT INTO #TOPEMPLOYEEDETAILS VALUES (1, 'DHRUV', 'VIKRAM')

INSERT INTO #TOPEMPLOYEEDETAILS VALUES (2, 'ARCAI', 'SHREE')

INSERT INTO #TOPEMPLOYEEDETAILS VALUES (3, 'SARA', 'VENGE')

SELECT * FROM #TOPEMPLOYEEDETAILS

CREATE TABLE #TOPSALARYDETAILS (EMPLOYEE_ID INT, SALARY_IN_DOLLARS FLOAT)

INSERT INTO #TOPSALARYDETAILS VALUES (1, 800000)
INSERT INTO #TOPSALARYDETAILS VALUES (2, 400000)
INSERT INTO #TOPSALARYDETAILS VALUES (3, 350000)

SELECT * FROM #TOPEMPLOYEEDETAILS
SELECT * FROM #TOPSALARYDETAILS 

SELECT A.FIRSTNAME, A.LASTNAME, B.SALARY_IN_DOLLARS  FROM 
#TOPEMPLOYEEDETAILS A INNER JOIN #TOPSALARYDETAILS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID

CREATE TABLE #CELLNUMBER (EMPLOYEE_ID INT, CELLNUMBER INT)

INSERT INTO #CELLNUMBER VALUES (1, 122333)
INSERT INTO #CELLNUMBER VALUES (2, 610947)

SELECT * FROM #TOPEMPLOYEEDETAILS
SELECT * FROM #CELLNUMBER


SELECT A.FIRSTNAME, A.LASTNAME, B.EMPLOYEE_ID FROM 
#TOPEMPLOYEEDETAILS A LEFT JOIN #CELLNUMBER B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID

SELECT GETDATE()
SELECT GETDATE() - 7

SELECT DATEPART(YYYY,GETDATE()) AS YEAR
SELECT DATEPART(MM,GETDATE()) AS MONTH
SELECT DATEADD(MONTH, 2, GETDATE())

SELECT TOP 10 * FROM Production.WorkOrder

SELECT WorkOrderID, ProductID, StartDate, EndDate,  DATEDIFF(DAY, StartDate, EndDate) AS DIFFD
FROM Production.WorkOrder

SELECT WorkOrderID, ProductID, StartDate, EndDate, DueDate, DATEDIFF(DAY, StartDate, EndDate) AS DIFFD1, DATEDIFF(DAY, DIFFD1, DueDate)
FROM Production.WorkOrder

SELECT * FROM #TOPSALARYDETAILS

SELECT AVG(SALARY_IN_DOLLARS) FROM #TOPSALARYDETAILS

